### ISSUE TITLE
Delayed restart activity in MainActivity and OneSheeldApplication

### ISSUE THREAD

**Issue by LiliWeiSE** [Integreight/1Sheeld-Android-App#4]
Hello developers of OneSheeld,

Can I open an issue here? Thanks.
I have found that `AlarmManager.set()` is used in `MainActivity` and `OneSheeldApplication` to set a `PendingIntent` to restart the activity after being destroyed in a very small time interval.
But this API may not send the intent in time on devices newer than KitKat. As I found in [API guide](http://developer.android.com/intl/zh-cn/reference/android/app/AlarmManager.html#set%28int,%20long,%20android.app.PendingIntent%29), alarm set by this API may be deferred sometime so that the activity will not be restarted in that small time interval as expected.

Using API `setExact` will make sure to send the alarm at that exact time.
Hope this information is useful for you. :)

Thanks a lot.

**Comment by isso** [comment]
@frankFic Thanks Frank, we will do it as you proposed in out next release. :)

Please let us know if you found more of these issues.

**Comment by LiliWeiSE** [comment]
@iSsO Thanks for your confirmation. I will report if I find any other issues. :)

**Comment by isso** [comment]
@frankFic The suggestions you mentioned has been added to our latest release v1.7.0 :)
